### ISSUE TITLE
yallist 3.1.0 not compatible with node 5 (5.12.0).

### ISSUE THREAD

**Issue by damellis** [isaacs/yallist#21]
I'm getting the below error when trying to do an `node yallist.js` with yallist 3.1.0 and node 5.12.0. If I switch to yallist 3.0.3, it works. 

```
/Users/mellisd/Source/libxmljs/node_modules/yallist/yallist.js:323
Yallist.prototype.splice = function (start, deleteCount, ...nodes) {
                                                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by isaacs** [comment]
Fixed on 3.1.1.

There will never be another 3.x release.

Please stop using Node 4.  It's insecure.  The node community has moved on.
